name: david-workflow
on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: printing name
              run: echo "Hello David"
            - name: printing occupation
              run: echo "i am a data scientist"